In [1]:
import os
import pandas as pd
import matplotlib.pyplot as plt
import math
import duckdb
import numpy as np
# Display all columns
pd.set_option('display.max_columns', None)

# Set max column width to a large value
pd.set_option('display.max_colwidth', None)

# Create a new DuckDB database file
con = duckdb.connect('my_database.duckdb')

In [2]:
import pandas as pd
import re

# Read the CSV file line by line
file_path = 'gnoweth_decoded.csv'
lines = []

with open(file_path, 'r') as file:
    lines = file.readlines()

# Initialize dictionaries to store lines for each transaction type
transaction_dict = {}

# Function to parse fields without combining text between single quotes
def parse_line(line):
    fields = line.split(',')
    fields = [field.strip() for field in fields]
    return fields

# Iterate over each line to categorize it based on the 6th field
for line in lines:
    fields = parse_line(line.strip())
    if len(fields) > 5:  # Ensure there are at least 6 fields after cleaning
        transaction_type = fields[5]
        if transaction_type not in transaction_dict:
            transaction_dict[transaction_type] = []
        transaction_dict[transaction_type].append(fields)

# Create separate DataFrames for each transaction type
dataframes = {}
for transaction_type, data in transaction_dict.items():
    # Determine the number of columns for this transaction type
    num_columns = max(len(fields) for fields in data)
    # Pad the data with empty strings to ensure all rows have the same number of columns
    padded_data = [fields + [''] * (num_columns - len(fields)) for fields in data]
    # Create DataFrame
    df = pd.DataFrame(padded_data, columns=[f'Field_{i+1}' for i in range(num_columns)])
    dataframes[transaction_type] = df

# Print out the names of the created DataFrames
for transaction_type in dataframes.keys():
    print(f'Created DataFrame: {transaction_type}')

SwapFeePercentageChanged = dataframes['SwapFeePercentageChanged']

Created DataFrame: Transfer
Created DataFrame: SwapFeePercentageChanged
Created DataFrame: Approval
Created DataFrame: OracleEnabledChanged

In [3]:
SwapFeePercentageChanged

,Field_1,Field_2,Field_3,Field_4,Field_5,Field_6,Field_7,Field_8,Field_9,Field_10,Field_11,Field_12,Field_13,Field_14,Field_15,Field_16
0,12505422,124,147,0x0e5c53950574cb933da47d5a885ae7f134849f43fa77eb818d9efd5cc65dbed0,0xF4C0DD9B82DA36C07605df83c8a416F11724d88b,SwapFeePercentageChanged,3100000000000000,None,None,None,None,None,None,None,None,None
1,12654826,142,225,0x7aadce84f11aa371f3ae09e56fbd46db03da1d3723d6df345fbde0f9a71548c1,0xF4C0DD9B82DA36C07605df83c8a416F11724d88b,SwapFeePercentageChanged,2800000000000000,None,None,None,None,None,None,None,None,None
2,12693310,154,329,0xd2bb72c0cfcea82cd4f7c3ff02fe7fe5b52bae983a71dfa0b746829d3233c0d5,0xF4C0DD9B82DA36C07605df83c8a416F11724d88b,SwapFeePercentageChanged,2600000000000000,None,None,None,None,None,None,None,None,None
3,12859412,201,293,0xf4241a0d9993a2d2ef6c0ae84fd35686f1e164ce804735ec10486d568959979d,0xF4C0DD9B82DA36C07605df83c8a416F11724d88b,SwapFeePercentageChanged,2400000000000000,None,None,None,None,None,None,None,None,None
4,12947811,174,247,0xf7f076531287b019582dd85bba1d180023a46553268e6bb10cb725e0bfff5ab0,0xF4C0DD9B82DA36C07605df83c8a416F11724d88b,SwapFeePercentageChanged,2600000000000000,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7395,20000617,90,327,0x3ee97d17961dea30bd4ce8493cc083baca87a861e81d39fab6ad47b9e954c0a0,0xF4C0DD9B82DA36C07605df83c8a416F11724d88b,SwapFeePercentageChanged,3000000000000000,None,None,None,None,None,None,None,None,None
7396,20000689,120,400,0xf5f175a6c342ad634e4837689c2d871617f1370496e6d20c86170003d1e39999,0xF4C0DD9B82DA36C07605df83c8a416F11724d88b,SwapFeePercentageChanged,600000000000000,None,None,None,None,None,None,None,None,None
7397,20000689,120,406,0xf5f175a6c342ad634e4837689c2d871617f1370496e6d20c86170003d1e39999,0xF4C0DD9B82DA36C07605df83c8a416F11724d88b,SwapFeePercentageChanged,3000000000000000,None,None,None,None,None,None,None,None,None
7398,20000710,48,361,0x0109b0776f9ce78e0d1a590a4b6380280cefab4a97eb5d2d1e18b2cf4f5e480b,0xF4C0DD9B82DA36C07605df83c8a416F11724d88b,SwapFeePercentageChanged,600000000000000,None,None,None,None,None,None,None,None,None
7399,20000710,48,367,0x0109b0776f9ce78e0d1a590a4b6380280cefab4a97eb5d2d1e18b2cf4f5e480b,0xF4C0DD9B82DA36C07605df83c8a416F11724d88b,SwapFeePercentageChanged,3000000000000000,None,None,None,None,None,None,None,None,None

In [4]:
selected_columns = {'Field_1': 'block_number', 'Field_3': 'log_index', 'Field_4': 'transaction_hash', 'Field_6':'event', 'Field_7': 'fee'}
SwapFeePercentageChanged = SwapFeePercentageChanged[list(selected_columns.keys())].rename(columns=selected_columns)

In [5]:
SwapFeePercentageChanged

,block_number,log_index,transaction_hash,event,fee
0,12505422,147,0x0e5c53950574cb933da47d5a885ae7f134849f43fa77eb818d9efd5cc65dbed0,SwapFeePercentageChanged,3100000000000000
1,12654826,225,0x7aadce84f11aa371f3ae09e56fbd46db03da1d3723d6df345fbde0f9a71548c1,SwapFeePercentageChanged,2800000000000000
2,12693310,329,0xd2bb72c0cfcea82cd4f7c3ff02fe7fe5b52bae983a71dfa0b746829d3233c0d5,SwapFeePercentageChanged,2600000000000000
3,12859412,293,0xf4241a0d9993a2d2ef6c0ae84fd35686f1e164ce804735ec10486d568959979d,SwapFeePercentageChanged,2400000000000000
4,12947811,247,0xf7f076531287b019582dd85bba1d180023a46553268e6bb10cb725e0bfff5ab0,SwapFeePercentageChanged,2600000000000000
...,...,...,...,...,...
7395,20000617,327,0x3ee97d17961dea30bd4ce8493cc083baca87a861e81d39fab6ad47b9e954c0a0,SwapFeePercentageChanged,3000000000000000
7396,20000689,400,0xf5f175a6c342ad634e4837689c2d871617f1370496e6d20c86170003d1e39999,SwapFeePercentageChanged,600000000000000
7397,20000689,406,0xf5f175a6c342ad634e4837689c2d871617f1370496e6d20c86170003d1e39999,SwapFeePercentageChanged,3000000000000000
7398,20000710,361,0x0109b0776f9ce78e0d1a590a4b6380280cefab4a97eb5d2d1e18b2cf4f5e480b,SwapFeePercentageChanged,600000000000000
7399,20000710,367,0x0109b0776f9ce78e0d1a590a4b6380280cefab4a97eb5d2d1e18b2cf4f5e480b,SwapFeePercentageChanged,3000000000000000

In [6]:
con.execute('CREATE TABLE gnoweth_fee_change AS SELECT * FROM SwapFeePercentageChanged').fetchdf()

# Commit the changes
con.commit()

# Close the connection
con.close()